config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"

  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :create, :show, :destroy]
  resources :publicrecipes, only: [:index]
  resources :shoppinglist, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index; end

  def new; end

  def create; end

  def destroy; end
end

app/controllers/publicrecipes_controller.rb
class PublicrecipesController < ApplicationController
  def index; end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index; end

  def new; end

  def create; end

  def show; end

  def destroy; end
end

app/controllers/shoppinglist_controller.rb
class ShoppinglistController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<h1>Under construction</h1>

app/views/foods/new.html.erb
<h1>Add New Food</h1>

<%= form_with model: @food, url: foods_path do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.submit "Add Food" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </main>
  </body>
</html>

app/views/publicrecipes/index.html.erb
<h1>Under construction</h1>

app/views/recipes/index.html.erb
<h1>Under construction</h1>

app/views/recipes/show.html.erb
<h1>Under construction</h1>

app/views/shoppinglist/index.html.erb
<h1>Under construction</h1>